spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  application:
    name: todo-list-api
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT}
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
  api-docs:
    path: /v1/api-docs
  packages-to-scan: br.com.eihror.todo_list
  paths-to-match:
    - /todo/**
    - /auth/**
    - /user/**

logging:
  level:
    org.springframework.security: DEBUG
